### ISSUE TITLE
Move tutorial with LC circuit into precice/tutorials

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/matlab-bindings#29]
The MATLAB bindings provide a [LC circuit tutorial](https://github.com/precice/matlab-bindings/tree/develop/tutorial). From the general content and structure this is a similar case to the precice/elastictube1d that was moved / is being moved to precice/tutorials.

# ToDos:

- [x] update general structure.
- [x] update documenation and provide documentation on website.
- [x] move this tutorial to `precice/tutorials`

**Comment by BenjaminRodenberg** [comment]
We can close this issue. I already deleted the tutorial here via https://github.com/precice/matlab-bindings/commit/635525e28cd06b11e4aebbb242ef12f7efe757fb and https://github.com/precice/tutorials/pull/480 will soon be merged.
